export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const LOGOUT_PROFILE_REQUEST = "LOGOUT_PROFILE_REQUEST";
export const LOGOUT_PROFILE_SUCCESS = "LOGOUT_PROFILE_SUCCESS";
export const LOGOUT_PROFILE_FAIL = "LOGOUT_PROFILE_FAIL";

export const LOGIN_PROFILE_REQUEST = "LOGIN_PROFILE_REQUEST";
export const LOGIN_PROFILE_SUCCESS = "LOGIN_PROFILE_SUCCESS";
export const LOGIN_PROFILE_FAIL = "LOGIN_PROFILE_FAIL";

export const REGISTER_PROFILE_REQUEST = "REGISTER_PROFILE_REQUEST";
export const REGISTER_PROFILE_SUCCESS = "REGISTER_PROFILE_SUCCESS";
export const REGISTER_PROFILE_FAIL = "REGISTER_PROFILE_FAIL";

export const ACTIVATION_EMAIL_REQUEST = "ACTIVATION_EMAIL_REQUEST";
export const ACTIVATION_EMAIL_SUCCESS = "ACTIVATION_EMAIL_SUCCESS";
export const ACTIVATION_EMAIL_FAIL = "ACTIVATION_EMAIL_FAIL";
